### PR TITLE
Kastaldi

### PR DESCRIPTION
**Pull request by kastaldi**
I have a custom contextmenu that doesn't work anymore that doesn't work anymore when I use the timepicker plugin.
I added "contextmenu" setting, true or false. Default is false. if true you can call contextmenu right clicking the box. If false, timepicker is shown when you click right mouse button. You can use it when you have a custom context menu . I also modified the index.html ".standard" input to show you how it works. Hope I didn't break anything because it is the first time I use github with vscode.

### CODE REVIEW

**Comment by loebi-ch** [comment]
> Sorry, the real js diff isn't so large. I just added "contextmenu:false" to settings and modified two functions, onInputElementDragSelectContextMenu and onInputElementMouseDown.

I've been just wondering why the diff looks so strange... Hard to find where you made some changes...

**Comment by kastaldi** [comment]
I'll try to sort this mess. :(

**Comment by loebi-ch** [comment]
> I'll try to sort this mess. :(

It's okay, you don't have to do anything. Thanx to your info about the changes, I was able to find them.

Just give me some more minutes and I will release a new version with your valuable input. I really appreciate that!

**Comment by kastaldi** [comment]
Thanks!

**Comment by loebi-ch** [comment]
You'll find new configuration option ```contextmenu``` in version 2.6.2.

**Pull request closed without merging**
